FROM python:3.14-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        gcc \
        libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the dependency files first to leverage Docker layer caching
COPY pyproject.toml uv.lock ./
COPY ./src /app/src/
COPY alembic.ini ./
COPY ./alembic /app/alembic/


# Install dependencies before installing the project
RUN uv sync --frozen --no-install-project --no-dev

# Ensure playwright installs globally and can be read by appuser
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
RUN uv run playwright install chromium \
    && uv run playwright install-deps chromium \
    && chmod -R 755 /ms-playwright


# Now copy the source code and install the project itself
COPY ./src /app/src/
RUN uv sync --frozen --no-dev

RUN useradd -m appuser \
    && mkdir -p /watched_folder \
    && chown -R appuser:appuser /app \
    && chown -R appuser:appuser /watched_folder

USER appuser

# Put the virtual environment generated by uv on the path
ENV PATH="/app/.venv/bin:$PATH"

CMD ["uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
