<<<<<<< HEAD
FROM python:3.14-slim
=======
FROM python:3.13-slim
>>>>>>> 6894f48 (chore(merge): ensure alignment with main branch)

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        gcc \
        libpq-dev \
    && rm -rf /var/lib/apt/lists/*

<<<<<<< HEAD
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the dependency files first to leverage Docker layer caching
COPY pyproject.toml uv.lock ./
COPY ./src /app/src/
COPY alembic.ini ./
COPY ./alembic /app/alembic/

# Install dependencies before installing the project
RUN uv sync --frozen --no-install-project --no-dev

# Now copy the source code and install the project itself
COPY ./src /app/src/
RUN uv sync --frozen --no-dev

RUN useradd -m appuser \
    && mkdir -p /watched_folder \
    && chown -R appuser:appuser /app \
    && chown -R appuser:appuser /watched_folder

USER appuser

# Put the virtual environment generated by uv on the path
ENV PATH="/app/.venv/bin:$PATH"

CMD ["uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
=======
COPY . /app/

RUN pip install --upgrade uv
RUN uv sync --no-dev

RUN uv run playwright install chromium
RUN uv run playwright install-deps chromium

CMD ["uv", "run", "uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
>>>>>>> 6894f48 (chore(merge): ensure alignment with main branch)
