"""
Add user_priority column to print_jobs.

Revision ID: 3dc1a2df7d43
Revises: 0001
Create Date: 2026-03-31 10:48:58.154556

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3dc1a2df7d43"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Check if column exists first before adding
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns("print_jobs")]

    if "user_priority" not in columns:
        op.add_column("print_jobs", sa.Column("user_priority", sa.Float(), nullable=True))

        # Backfill existing records with a default priority of 0.0
        op.execute("UPDATE print_jobs SET user_priority = 0.0 WHERE user_priority IS NULL")

        # Now that data is backfilled, we can safely make the column non-nullable
        if conn.dialect.name == "sqlite":
            with op.batch_alter_table("print_jobs") as batch_op:
                batch_op.alter_column("user_priority", nullable=False)
        else:
            op.alter_column("print_jobs", "user_priority", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("print_jobs", "user_priority")
    # ### end Alembic commands ###
