"""
Add service configs table

Revision ID: c7b2a3be6b70
Revises: 3dc1a2df7d43
Create Date: 2026-05-14 05:12:26.017662

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c7b2a3be6b70'
down_revision: Union[str, Sequence[str], None] = '3dc1a2df7d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.Column('credential', sa.String(), nullable=True),
    sa.Column('target_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_configs_id'), 'service_configs', ['id'], unique=False)
    op.create_index(op.f('ix_service_configs_service_name'), 'service_configs', ['service_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_configs_service_name'), table_name='service_configs')
    op.drop_index(op.f('ix_service_configs_id'), table_name='service_configs')
    op.drop_table('service_configs')
    # ### end Alembic commands ###
